### ISSUE TITLE
Module 4 Lab incorrect instruction

### ISSUE THREAD

**Issue by bgirardot** [FOSS4GAcademy/GST101FOSS4GLabs#4]
Step 19 is to make the background blue for water, but the instruction says:

>Set the RBG value to: 225-255-255. 

Which just sets it to the existing background color, white.

**Comment by geomenke** [comment]
Actually the RBG value of 225-255-255 will result in a light blue color. Make sure the R value is 225 not 255.

Kurt

 

**************************

Kurt Menke, GISP

Bird’s Eye View 

www.BirdsEyeViewGIS.com <http://www.birdseyeviewgis.com/>  

Work: 505-265-0243

Cell: 505-362-1776

**Comment by bgirardot** [comment]
Oh my, I didn't see that at all, I saw 255's for all three.

Sorry for the confusion.

Cheers,
Blake
